travis:
  secure:
    BINSTAR_TOKEN: pmCfE8dW7dif86mmh7S1ZQwTLXTysSoA5lChh+9TYljwpQDb46bRwOyw52+KY3gNa4dcn0VdRuSSEEA1PnN5B8LGh7j5J5hNaPnkpJLHKzNrEf8Zhh5MPSu/Y0cIbcfwmJilDlXqycsnfV1hbBF9bkg2ZdJy3DSf39RMSLB3lnZS45UKyEQ6TQKzX6lMiLQYHshBTbOJHrZ38itQIM9ygAYpSqkyGDUic+V3cHrfXdTFlemJd00BS4SZbfy+XOrgpeGLzcBOw6p8/Hh4kqPeCfRyY130ZSsVlisXi2IyE0Qnrca02alx6OdoU9cVKw4oAviQ3jpggURXp2D4wJg1W6RO5eOSg71qFV7ffgcdr1aHKuZxiUYUswesWQhqqXeYFTKlGAGLP/VbeVdXMeU+v1oTL7xJrmNOQB/CySM6laRpB7G7wIrCO68mz09rDxeoFUg97fCFsWuCnjQhm15/73hg1J0E4/fHbxetgeb8devH6d/LrnfoJUyyzw3desx7XozGKdkmNFtuzHRdNswvemLrjdaOe6In1A3r+U6YvF+tLHGZ8FhT1eIyAhHexFDr8DhsMemAuPzP9lnLS1Vf7uZWBra8DmR+Sdu3eKG8NLndtHGQSd6slyg1ocwkjkhywV/o/FyTFbcJe5qRCHinNnMBKGdF61yCkWQ8MevszyM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
