travis:
  secure:
    BINSTAR_TOKEN: crfwV2IbRUFiDvrX9JtpDd0Y7R/1bzL6mibD24DSRF4ZEtYtibNJRh+JZ4fpUY0YLbLqTYTrP1QgbBjkCy2EswdYmNFoEu7tL4JqXSWPlKahPbv/aR9c38CJ+HLUR25rN6uUxUL0RTeQnMt4U891A+y4SeAMwE4pOKwJVkwmSK/FzVa7n+zaJilD9E2Sfd5HxpsLURT0jYcWTJs2K825Ntj4NtoDhgK6Zw2p4ELUzJgPtkoZGh55yOHdWhadrMPRmYZ8FXjRWHoboR33PS+eFxDzun4sBhflsfPwR/A/D2IY9GbxRiFwqVrFb+HjIFjBtTKN8vCUoaTs8n9huXNwks+GBQTjmZtDnSFgl+/qdZLnGkvfm6cOjW15hwqxo4BsiVSDk2kWoL01/lbLyStRLg/HWDkAFwr5vHtVl/XytSuPMTwopDAgDyBR8M7aK1sGe4gzTYFGUUEiBL1zBT6R4tG+LY3iG2cvJMwiYlvEGDkF7sFAV0hW9vxDk9sv01x5SyAGbMR1RWs8UN4f2t0L2bkdgkvgQwqn0rivuLawy9LLDY/vpLj2ql2ohlJp95WrnyKju3SgcN9qOd87baYtpdyob8UspWztOzkrk3kEhaeqD0fEDFhUoh7iRqG3j1MHq0zz+wP5FPb3sbIdS5EDW8c9G+/lUphFb0SvubgrbBU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
